version: "3.9"
services:
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        restart: always
        command: [mongod]
    web:
        build: .
        ports: 
            - "3000:3000"
        restart: always
        environment:
            - HOST=localhost
            - UPLOAD_LIMIT=70000
            - DB_HOST=${DB_HOST}
            - DB_USER=${DB_USER}
            - DB_PWD=${DB_PWD}
            - DB_NAME=${DB_NAME}
            - ACCTOKEN_SECRET=${ACCTOKEN_SECRET}
            - ACCTOKEN_LIFE=${ACCTOKEN_LIFE}
            